### ISSUE TITLE
Make EarthMobsMods's Monsters not spawn in `forge:no_default_monsters` biome tag

### ISSUE THREAD

**Issue by TelepathicGrunt** [baguchan/EarthMobs#10]
Some biome mods are making a  `forge:no_default_monsters` biome tag to mark that their biomes should not have monsters in it just like how Mushroom Biomes and Deep Dark do not spawn monsters. If you can add a check for this biome tag to not spawn your mob's monsters in it, that would be great!
![image](https://github.com/baguchan/EarthMobs/assets/40846040/ffa1931d-b99e-49a1-8890-4cc6ce6308cf)

**Comment by baguchi** [comment]
will do!

**Comment by baguchi** [comment]
complete!
