### ISSUE TITLE
Harder Flesh doesn't show up in creative menu or in JEI

### ISSUE THREAD

**Issue by sigmastar00** [baguchan/EarthMobs#12]
## Installed Versions:
- Minecraft 1.20.1
- Forge 47.2.21
- Baguslib 4.4.0
- JEI 15.3.0.4
- Earth Mobs 10.3.1

## Issue Description
The harder flesh item that drops from the bouldering zombie can't be found in either the creative menu, or in the jei menu. You also can't see the recipe for the toughness potion in jei either.

**Comment by baguchi** [comment]
1.20.1 is not have harden flesh for now... sorry

**Comment by sigmastar00** [comment]
The item still drops from the bouldering zombies that spawn in the world so I'm not sure what you mean by it not being in 1.20.1

**Comment by baguchi** [comment]
oh wait I was wrong
I accident not add it...
I'll add in next update sorry

**Comment by baguchi** [comment]
strange. after the look at my github already registry about my potion....
mayby jei bug...?
