### ISSUE TITLE
Husk counterparts for Bouldering/Lobber Zombies

### ISSUE THREAD

**Issue by 256smash** [baguchan/EarthMobs#19]
I once talked about this idea on the Discord server for a mod.

Since these zombies have Drowned counterparts, I have the unusual idea that Bouldering Husk can be found in Eroded/Wooded Badlands, since these biomes are similar to mountains, and Lobber Husk will shoot its own projectile to impose an enhancement effect on the player that will be increased by a factor of 2.

That would be interesting.

**Comment by baguchi** [comment]
It is planning too! so Please look forward to it :)
