### ISSUE TITLE
mobs missing

### ISSUE THREAD

**Issue by violetkitty87** [baguchan/EarthMobs#2]
I see the muddy pig and moobloom on the main page of what the description of the mod is, but I don't see them in world or in config on the 1.18.1 version and don't see information for horned sheep or woolly cow or hyper rabbit on where to find them. Can we fix this please?

**Comment by violetkitty87** [comment]
i also see they dont exist in world yet either can we make this clearer on the link please

**Comment by LilGamerBean** [comment]
This is still an issue. I just had this mod into my game and can't find the moobloom in the world or find earth mobs anywhere in my game.

**Comment by baguchan** [comment]
I want back them but I'm not a pro modeler so It's hard to back sorry
but I'll remade them.....!

**Comment by baguchan** [comment]
oh also Muddy Pig is back in 1.18.2-0.7.0!

**Comment by LilGamerBean** [comment]
Is 1.18.1 fixed?
