### ISSUE TITLE
一部モブの重複したスポーン登録

### ISSUE THREAD

**Issue by Mechalopa** [baguchan/EarthMobs#2]
[Spawn Balance Utility](https://www.curseforge.com/minecraft/mc-mods/spawn-balance-utility) modで深紅の森のベビーガストやソウルサンドの谷のスケルトンウルフ、ウィザースケルトンウルフなどが重複してスポーン登録されていたのに気づいたので、報告します。

EarthBiomeModifierではphase == Phase.ADDのif文で全体が括られていないようなので、これが原因だと思います。
https://github.com/baguchan/EarthMobs/blob/master/src/main/java/baguchan/earthmobsmod/world/biome/EarthBiomeModifier.java

実際のスポーン率に影響があるのかは検証していませんが…

**Comment by baguchi** [comment]
細かい検証わざわざありがとうございます！
たしかに見落としてました(´・ω・`)<すみません
すぐ取り掛かります！

**Comment by baguchi** [comment]
修正しました！
