### ISSUE TITLE
[1.21 NeoForge] Crash when right clicking with an Axe on dirt 

### ISSUE THREAD

**Issue by Starexify** [baguchan/EarthMobs#22]
Mod Ver: 1.21-18.2.0
NeoForge Ver: 21.0.43

Issue: When I right click with an axe on a dirt block, it crashes. I don't know why but i guess an method is just unfinished maybe because I seee the method being BlockEvent$BlockToolModificationEvent.getToolAction() crash the game? I believe it has to do with the CommonEvents.onToolUsing(CommonEvents.java:97) method. So please check it out

Crash Report and Log:
[crash-2024-07-01_12.17.33-client.txt](https://github.com/user-attachments/files/16051407/crash-2024-07-01_12.17.33-client.txt)
[latest.log](https://github.com/user-attachments/files/16051409/latest.log)

**Comment by baguchi** [comment]
thanks for report!
will fix in next verison!

**Comment by Starexify** [comment]
> thanks for report! will fix in next verison!

Also crashes when right clicking with shovel. Got that only now when trying to make a path xD

**Comment by baguchi** [comment]
It will fix too! don't worry
