### ISSUE TITLE
1.21 NeoForge Crash on World Load

### ISSUE THREAD

**Issue by Zelioth** [baguchan/EarthMobs#24]
Earth Mobs 18.6.0
NeoForge 21.0.166
Minecraft 1.21

With Earth Mobs active I go to generate a world and it stops before generating and creates a crash report.

[crash-2024-08-08_00.12.55-server.txt](https://github.com/user-attachments/files/16537955/crash-2024-08-08_00.12.55-server.txt)
[latest.log](https://github.com/user-attachments/files/16537958/latest.log)
[Uploading debug.log…]()

**Comment by baguchi** [comment]
strange... I try with only EarthMobs and Bagus Lib... It's not happened
mayby some mod imcompability?
Beyond this, it may be difficult to understand what is causing the problem.

**Comment by baguchi** [comment]
nvm. It's my mod problem... we will solve soon

**Comment by baguchi** [comment]
fixed in 1.21-18.6.2. sorry for long take
