### ISSUE TITLE
ウシの足のアニメーションについて

### ISSUE THREAD

**Issue by Mechalopa** [baguchan/EarthMobs#26]
細かいことなのですが報告させて頂きます。
EarthCowAnimationをモデルに使用しているウシは、バニラのウシやもさもさのウシ、マグマウシより足の動きが遅いようで、滑るように移動しているように見えます。

**Comment by baguchi** [comment]
あー・・・それに関してですが、cow modelを使わずにアニメーションできるように(牛のmodelだと細かくanimationできないため)、少しアニメーションのテストしたときにうまくいかなかった感じですね・・・
あとで直しておきます

**Comment by baguchi** [comment]
修正しました！
