### ISSUE TITLE
Latest update, minecraft don't launch 

### ISSUE THREAD

**Issue by TheeMrCheeky** [baguchan/EarthMobs#29]
Latest forge, .57 on 1.19.2 and 
EarthMobs-1.19.2-4.1.0.jar

Well with this latest version of earth mobs, Minecraft won't launch.. I have a 149 other mods I think it may not be agreeing with one but it was fine until latest update. no crash log comes up either sadly..

**Comment by baguchan** [comment]
sorry for late :(
looks like I missed about mixin in the ```thunderHit``` method on PigMixin class
It will be fixed in the next version!
