### ISSUE TITLE
ゴールデンブロームとピンクデイジーについて

### ISSUE THREAD

**Issue by Mechalopa** [baguchan/EarthMobs#3]
ゴールデンブロームとピンクデイジーは以下の点でバニラの小さい花と異なると思います。
・火や溶岩の傍でも燃えない
・ピストンで押しても壊れない
・堆肥化できない
・植木鉢に植えられない
・植えた時に見た目がランダムにオフセットされない
・染料に加工できない
・`minecraft:small_flowers`ブロックタグに追加されていない(ミツバチが受粉しない、エンダーマンが持てない)

いくつか意図的かもしれませんが報告させて頂きます。

**Comment by baguchi** [comment]
ご報告ありがとうございます！
すぐに修正しておきます！

**Comment by baguchi** [comment]
修正しました！
