### ISSUE TITLE
1.20 port

### ISSUE THREAD

**Issue by gohkenytp** [baguchan/EarthMobs#40]
I ported this to 1.20 but you suddenly rejected it for no reason at all. Why is that? You could've done it too you know.

**Comment by baguchan** [comment]
because you send no detail pullrequest and persistent over and over again
also I do the myself for 1.20 port
please stop asking 1.20 port and annoying behavior

**Comment by gohkenytp** [comment]
Bruh, all I did is help you. Not try to annoy you non-stop. I'm not stupid you know.
