### ISSUE TITLE
1.20 port (Take 2)

### ISSUE THREAD

**Issue by gohkenytp** [baguchan/EarthMobs#41]
I'm sorry for annoying you non-stop. I just wanted this mod ported to 1.20. Besides, I'm too sure Minecraft 1.20.1 is released right away.

**Comment by baguchan** [comment]
...could you stop make issues like this?

**Comment by gohkenytp** [comment]
OK I will. I just wanted to let you know that I've should waited for your EarthMobs mod to be ported to 1.20. That's all!
