### ISSUE TITLE
Bouldering Zombie when Spawned with a sword has bad texture

### ISSUE THREAD

**Issue by WelpSTudent** [baguchan/EarthMobs#5]
![image](https://user-images.githubusercontent.com/63996164/165165222-c788fe0b-c029-4d97-9f48-15ec493dd661.png)
1.18.2
Look at his hands / arms

**Comment by baguchan** [comment]
![2022-04-26_06 32 41](https://user-images.githubusercontent.com/88538210/165178777-56f8a60f-9189-4183-8ef4-f7cdc00b1e79.png)
strenge..... When I let him equip him, nothing happened
