### ISSUE TITLE
[BUG] Adding redstone to any potion turns it into hyperspeed potion

### ISSUE THREAD

**Issue by BIG-Viljo** [baguchan/EarthMobs#7]
MC version: 1.18.2
Mod version: 0.8.3
Forge version: 40.1.22

Description:
Adding redstone to any potion (even base potions) in brewing stand turns it into 8 minute potion of hyperspeed, even the 8 minute potion of hyperspeed is then brewed into 8 minute potion of hyperspeed resulting into infinite cycle. Removing recipe for this potion using Crafttweaker doesn't work. I have to stop using this mod until this issue is fixed.

**Comment by baguchan** [comment]
fixed in 1.18.2-0.8.4!
